SUPPORTED_GARMENT_CLASSES = ["tshirt"]

CAPABILITIES_FIXTURE = {
    "patternAvailable": True,
    "simulationReadyTopologyAvailable": True,
    "authoredMaterialPresetAvailable": True,
    "conventionalGlbAvailable": True,
    "simToRenderBindingAvailable": True,
    "bindingReconstructionValidated": True,
    "actualClothSettleAvailable": True,
    "selfCollisionAvailable": False,
    "sourceImageTextureAvailable": False,
    "sourceCaptureRecordAvailable": True,
    "captureQualityScored": True,
    "visualObservationsAvailable": True,
    "garmentMaskAvailable": True,
    "garmentLandmarksAvailable": True,
    "editableCorrectionRecordAvailable": True,
    "tshirtParameterFitAvailable": True,
    "fittingQualityScored": True,
    "textureIdentityEvidenceAvailable": True,
    "pbrMaterialObservationAvailable": True,
    "geometryProposalInterfaceAvailable": True,
    "rawGeometryProposalRecordAvailable": True,
    "geometryProposalQualityScored": True,
    "rawGeometryTopologyDiagnosticsAvailable": True,
    "geometryCleanupRecommendationAvailable": True,
    "geometryCleanupExecutionAvailable": True,
    "geometrySemanticTransferAvailable": True,
    "geometryBoundaryClassificationAvailable": True,
    "geometryBindingCandidateAvailable": True,
    "providerProvenanceAvailable": True,
    "geometryProviderRegistryAvailable": True,
    "manualGeometryImportAdapterDeclared": True,
    "manualGeometryImportAssetAvailable": True,
    "externalGeometryProvidersConfigured": False,
    "cleanGeometryProposalAvailable": False,
    "personalizedAvatarAvailable": False,
    "skeletalFallbackAvailable": False,
    "zeroOneStaticAvailable": False,
    "zeroOneDynamicAvailable": False,
    "mobileOptimisedAuthoritativeAsset": False,
}
