from __future__ import annotations

from typing import Any

SCHEMA_VERSION = 1

HEX_64 = "^[0-9a-f]{64}$"
REL_PATH = "^(?!/)(?!.*(?:^|/)\\.\\.(?:/|$))(?!.*\\\\)[A-Za-z0-9._\\-/]+$"


def schema_registry() -> dict[str, dict[str, Any]]:
    return {
        "common.schema.json": _schema(
            "Closy common coordinate and artifact fields",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "coordinateConvention": _coordinate_convention(),
                "artifactRef": _artifact_ref(),
            },
            ["schemaVersion"],
        ),
        "garment-manifest.schema.json": _schema(
            "Closy garment package manifest",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "packageKind": {"const": "closy.garment"},
                "garmentId": {"type": "string", "pattern": "^garment\\."},
                "displayName": {"type": "string", "minLength": 1},
                "garmentClass": {"const": "tshirt"},
                "units": {"const": "metres"},
                "coordinateConvention": _coordinate_convention(),
                "status": {"enum": ["validated_fixture", "canonical_contract_ready"]},
                "avatar": _object(
                    {
                        "contractId": {"const": "avatar.closy_reference_v1"},
                        "version": {"type": "string"},
                        "path": _rel_path(),
                        "contentHash": _sha256(),
                        "sourceKind": {"const": "procedural_fixture"},
                    },
                    ["contractId", "version", "path", "contentHash", "sourceKind"],
                ),
                "canonicalPaths": _string_map(_rel_path()),
                "hashes": _string_map(_sha256()),
                "inventory": {"type": "array", "items": _artifact_ref()},
                "canonicalDigestDefinition": {"type": "object", "additionalProperties": True},
                "canonicalPackageDigest": _sha256(),
                "algorithmVersions": _string_map({"type": "string"}),
                "seed": {"type": "integer"},
                "buildProfile": {"type": "object", "additionalProperties": True},
                "capabilities": _capabilities(),
                "warnings": {"type": "array", "items": {"type": "string"}},
                "zeroOne": _object(
                    {
                        "staticAvailable": {"type": "boolean"},
                        "dynamicAvailable": {"type": "boolean"},
                        "required": {"type": "boolean"},
                    },
                    ["staticAvailable", "dynamicAvailable", "required"],
                ),
                "extensions": {"type": "object", "additionalProperties": True},
            },
            [
                "schemaVersion",
                "packageKind",
                "garmentId",
                "displayName",
                "garmentClass",
                "units",
                "coordinateConvention",
                "status",
                "avatar",
                "canonicalPaths",
                "hashes",
                "inventory",
                "canonicalPackageDigest",
                "algorithmVersions",
                "seed",
                "buildProfile",
                "capabilities",
                "warnings",
                "zeroOne",
            ],
        ),
        "provenance.schema.json": _schema(
            "Closy deterministic provenance graph",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "sourceKind": {"const": "procedural_fixture"},
                "allowExternalApis": {"const": False},
                "allowTrainingUse": {"const": False},
                "containsUserImagery": {"const": False},
                "containsPersonalBodyData": {"const": False},
                "coordinateConvention": _coordinate_convention(),
                "sourceConvention": _coordinate_convention(),
                "appliedConversionMatrix": {"type": "array"},
                "seed": {"type": "integer"},
                "fixedTimestamp": {"type": "string"},
                "stages": {"type": "array", "items": {"type": "object"}},
                "warnings": {"type": "array", "items": {"type": "string"}},
            },
            [
                "schemaVersion",
                "sourceKind",
                "allowExternalApis",
                "allowTrainingUse",
                "containsUserImagery",
                "containsPersonalBodyData",
                "coordinateConvention",
                "sourceConvention",
                "appliedConversionMatrix",
                "seed",
                "fixedTimestamp",
                "stages",
                "warnings",
            ],
        ),
        "capture-record.schema.json": _schema(
            "Closy immutable capture source record",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "recordId": {"type": "string", "pattern": "^capture\\."},
                "recordVersion": {"type": "string"},
                "recordType": {"const": "synthetic_fixture_capture"},
                "sourceKind": {"const": "synthetic_metadata_only"},
                "garmentId": {"type": "string", "pattern": "^garment\\."},
                "garmentClass": {"const": "tshirt"},
                "avatarContractId": {"const": "avatar.closy_reference_v1"},
                "coordinateConvention": _coordinate_convention(),
                "privacy": _object(
                    {
                        "containsUserImagery": {"const": False},
                        "containsPersonalBodyData": {"const": False},
                        "allowExternalApis": {"const": False},
                        "allowTrainingUse": {"const": False},
                        "consentRequired": {"const": False},
                        "deletionPolicy": {"const": "regenerable_fixture_no_user_data"},
                    },
                    [
                        "containsUserImagery",
                        "containsPersonalBodyData",
                        "allowExternalApis",
                        "allowTrainingUse",
                        "consentRequired",
                        "deletionPolicy",
                    ],
                ),
                "captureSession": {"type": "object", "additionalProperties": True},
                "views": {"type": "array", "minItems": 1, "items": {"type": "object"}},
                "immutability": _object(
                    {
                        "mutable": {"const": False},
                        "canonicalization": {"type": "string"},
                        "contentAddressable": {"const": True},
                        "sourceRecordHash": _sha256(),
                    },
                    ["mutable", "canonicalization", "contentAddressable", "sourceRecordHash"],
                ),
                "futureEditableArtifacts": {"type": "object", "additionalProperties": True},
            },
            [
                "schemaVersion",
                "recordId",
                "recordVersion",
                "recordType",
                "sourceKind",
                "garmentId",
                "garmentClass",
                "avatarContractId",
                "coordinateConvention",
                "privacy",
                "captureSession",
                "views",
                "immutability",
                "futureEditableArtifacts",
            ],
        ),
        "capture-quality.schema.json": _schema(
            "Closy capture quality report",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "qualityReportId": {"type": "string", "pattern": "^capture_quality\\."},
                "scorerVersion": {"type": "string"},
                "sourceRecordId": {"type": "string", "pattern": "^capture\\."},
                "sourceRecordHash": _sha256(),
                "overallStatus": {"enum": ["pass", "warn", "fail"]},
                "overallScore": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                "qualityThreshold": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                "viewCount": {"type": "integer", "minimum": 0},
                "viewScores": {"type": "array", "items": {"type": "object"}},
                "dimensionScores": {"type": "array", "items": {"type": "object"}},
                "policy": _object(
                    {
                        "requiresUserConsent": {"const": False},
                        "externalApiUseAllowed": {"const": False},
                        "trainingUseAllowed": {"const": False},
                        "rasterImagesAvailable": {"const": False},
                    },
                    [
                        "requiresUserConsent",
                        "externalApiUseAllowed",
                        "trainingUseAllowed",
                        "rasterImagesAvailable",
                    ],
                ),
                "warnings": {"type": "array", "items": {"type": "string"}},
                "nextRequiredArtifacts": {"type": "array", "items": {"type": "string"}},
            },
            [
                "schemaVersion",
                "qualityReportId",
                "scorerVersion",
                "sourceRecordId",
                "sourceRecordHash",
                "overallStatus",
                "overallScore",
                "qualityThreshold",
                "viewCount",
                "viewScores",
                "dimensionScores",
                "policy",
                "warnings",
                "nextRequiredArtifacts",
            ],
        ),
        "visual-observations.schema.json": _schema(
            "Closy visual understanding observations",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "visualUnderstandingId": {"type": "string", "pattern": "^visual\\."},
                "stageVersion": {"type": "string"},
                "sourceRecordId": {"type": "string", "pattern": "^capture\\."},
                "sourceRecordHash": _sha256(),
                "garmentClass": {"const": "tshirt"},
                "provider": _object(
                    {
                        "type": {"const": "deterministic_synthetic_fixture"},
                        "automaticSegmentation": {"const": False},
                        "interactiveEditable": {"const": True},
                        "externalApis": {"const": False},
                        "trainingUse": {"const": False},
                    },
                    [
                        "type",
                        "automaticSegmentation",
                        "interactiveEditable",
                        "externalApis",
                        "trainingUse",
                    ],
                ),
                "coordinateSpaces": {"type": "object", "additionalProperties": True},
                "views": {"type": "array", "minItems": 1, "items": {"type": "object"}},
                "aggregate": {"type": "object", "additionalProperties": True},
                "warnings": {"type": "array", "items": {"type": "string"}},
                "integrity": _object({"visualRecordHash": _sha256()}, ["visualRecordHash"]),
            },
            [
                "schemaVersion",
                "visualUnderstandingId",
                "stageVersion",
                "sourceRecordId",
                "sourceRecordHash",
                "garmentClass",
                "provider",
                "coordinateSpaces",
                "views",
                "aggregate",
                "warnings",
                "integrity",
            ],
        ),
        "correction-record.schema.json": _schema(
            "Closy editable correction record",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "correctionRecordId": {"type": "string", "pattern": "^correction\\."},
                "recordVersion": {"type": "string"},
                "visualUnderstandingId": {"type": "string", "pattern": "^visual\\."},
                "visualRecordHash": _sha256(),
                "state": {"enum": ["empty_editable_baseline", "edited"]},
                "editable": {"type": "boolean"},
                "privacy": _object(
                    {
                        "containsUserImagery": {"const": False},
                        "containsPersonalBodyData": {"const": False},
                        "allowExternalApis": {"const": False},
                        "allowTrainingUse": {"const": False},
                    },
                    [
                        "containsUserImagery",
                        "containsPersonalBodyData",
                        "allowExternalApis",
                        "allowTrainingUse",
                    ],
                ),
                "allowedOperations": {"type": "array", "items": {"type": "string"}},
                "operations": {"type": "array", "items": {"type": "object"}},
                "integrity": _object({"correctionRecordHash": _sha256()}, ["correctionRecordHash"]),
            },
            [
                "schemaVersion",
                "correctionRecordId",
                "recordVersion",
                "visualUnderstandingId",
                "visualRecordHash",
                "state",
                "editable",
                "privacy",
                "allowedOperations",
                "operations",
                "integrity",
            ],
        ),
        "tshirt-fit-report.schema.json": _schema(
            "Closy T-shirt fit report",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "fitReportId": {"type": "string", "pattern": "^fit\\."},
                "fitterVersion": {"type": "string"},
                "sourceVisualUnderstandingId": {"type": "string", "pattern": "^visual\\."},
                "sourceVisualRecordHash": _sha256(),
                "garmentClass": {"const": "tshirt"},
                "method": {"type": "string"},
                "status": {"enum": ["pass", "warn", "fail"]},
                "accepted": {"type": "boolean"},
                "priorParameters": {"type": "object", "additionalProperties": {"type": "number"}},
                "fittedParameters": {"type": "object", "additionalProperties": {"type": "number"}},
                "parameterDeltas": {"type": "object", "additionalProperties": {"type": "number"}},
                "parameterConfidence": {
                    "type": "object",
                    "additionalProperties": {"type": "number"},
                },
                "inputMeasurements": {"type": "object", "additionalProperties": {"type": "number"}},
                "losses": {"type": "object", "additionalProperties": True},
                "thresholds": {"type": "object", "additionalProperties": {"type": "number"}},
                "alternatives": {"type": "array", "items": {"type": "object"}},
                "warnings": {"type": "array", "items": {"type": "string"}},
                "integrity": _object({"fitReportHash": _sha256()}, ["fitReportHash"]),
            },
            [
                "schemaVersion",
                "fitReportId",
                "fitterVersion",
                "sourceVisualUnderstandingId",
                "sourceVisualRecordHash",
                "garmentClass",
                "method",
                "status",
                "accepted",
                "priorParameters",
                "fittedParameters",
                "parameterDeltas",
                "parameterConfidence",
                "inputMeasurements",
                "losses",
                "thresholds",
                "alternatives",
                "warnings",
                "integrity",
            ],
        ),
        "texture-identity.schema.json": _schema(
            "Closy texture identity report",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "textureIdentityId": {"type": "string", "pattern": "^texture\\."},
                "stageVersion": {"type": "string"},
                "sourceRecordId": {"type": "string", "pattern": "^capture\\."},
                "sourceRecordHash": _sha256(),
                "sourceVisualUnderstandingId": {"type": "string", "pattern": "^visual\\."},
                "sourceVisualRecordHash": _sha256(),
                "sourceFitReportId": {"type": "string", "pattern": "^fit\\."},
                "sourceFitReportHash": _sha256(),
                "status": {"enum": ["pass", "warn", "fail"]},
                "sourceTextureAvailable": {"type": "boolean"},
                "generatedAtlasAvailable": {"type": "boolean"},
                "textureProjectionRun": {"type": "boolean"},
                "observedMaterialRegions": {
                    "type": "array",
                    "minItems": 1,
                    "items": {"type": "object"},
                },
                "projectionPlan": {"type": "object", "additionalProperties": True},
                "pbrSafety": {"type": "object", "additionalProperties": True},
                "warnings": {"type": "array", "items": {"type": "string"}},
                "integrity": _object({"textureIdentityHash": _sha256()}, ["textureIdentityHash"]),
            },
            [
                "schemaVersion",
                "textureIdentityId",
                "stageVersion",
                "sourceRecordId",
                "sourceRecordHash",
                "sourceVisualUnderstandingId",
                "sourceVisualRecordHash",
                "sourceFitReportId",
                "sourceFitReportHash",
                "status",
                "sourceTextureAvailable",
                "generatedAtlasAvailable",
                "textureProjectionRun",
                "observedMaterialRegions",
                "projectionPlan",
                "pbrSafety",
                "warnings",
                "integrity",
            ],
        ),
        "geometry-proposal.schema.json": _schema(
            "Closy raw visual geometry proposal report",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "proposalId": {"type": "string", "pattern": "^proposal\\."},
                "stageVersion": {"type": "string"},
                "garmentId": {"type": "string", "pattern": "^garment\\."},
                "garmentClass": {"const": "tshirt"},
                "sourceRecordId": {"type": "string", "pattern": "^capture\\."},
                "sourceRecordHash": _sha256(),
                "sourceVisualUnderstandingId": {"type": "string", "pattern": "^visual\\."},
                "sourceVisualRecordHash": _sha256(),
                "sourceFitReportId": {"type": "string", "pattern": "^fit\\."},
                "sourceFitReportHash": _sha256(),
                "sourceTextureIdentityId": {"type": "string", "pattern": "^texture\\."},
                "sourceTextureIdentityHash": _sha256(),
                "provider": {"type": "object", "additionalProperties": True},
                "request": {"type": "object", "additionalProperties": True},
                "rawProposal": {"type": "object", "additionalProperties": True},
                "cleanProposal": {"type": "object", "additionalProperties": True},
                "alignmentRules": {"type": "object", "additionalProperties": True},
                "geometryAudit": {"type": "object", "additionalProperties": True},
                "quality": {"type": "object", "additionalProperties": True},
                "policy": {"type": "object", "additionalProperties": True},
                "integrity": _object({"geometryProposalHash": _sha256()}, ["geometryProposalHash"]),
            },
            [
                "schemaVersion",
                "proposalId",
                "stageVersion",
                "garmentId",
                "garmentClass",
                "sourceRecordId",
                "sourceRecordHash",
                "sourceVisualUnderstandingId",
                "sourceVisualRecordHash",
                "sourceFitReportId",
                "sourceFitReportHash",
                "sourceTextureIdentityId",
                "sourceTextureIdentityHash",
                "provider",
                "request",
                "rawProposal",
                "cleanProposal",
                "alignmentRules",
                "geometryAudit",
                "quality",
                "policy",
                "integrity",
            ],
        ),
        "clean-geometry-proposal.schema.json": _schema(
            "Closy clean geometry proposal report",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "proposalId": {"type": "string", "pattern": "^proposal\\."},
                "stageVersion": {"type": "string"},
                "garmentId": {"type": "string", "pattern": "^garment\\."},
                "garmentClass": {"const": "tshirt"},
                "sourceRawProposalId": {"type": "string", "pattern": "^proposal\\."},
                "sourceRawProposalHash": _sha256(),
                "sourceProviderRegistryId": {
                    "type": "string",
                    "pattern": "^provider_registry\\.",
                },
                "sourceProviderRegistryHash": _sha256(),
                "sourceRawTopologyReportId": {
                    "type": ["string", "null"],
                    "pattern": "^topology\\.",
                },
                "sourceRawTopologyReportHash": {
                    "anyOf": [_sha256(), {"type": "null"}],
                },
                "sourceGeometryCleanupPlanId": {
                    "type": ["string", "null"],
                    "pattern": "^cleanup_plan\\.",
                },
                "sourceGeometryCleanupPlanHash": {
                    "anyOf": [_sha256(), {"type": "null"}],
                },
                "rawProposal": {"type": "object", "additionalProperties": True},
                "cleanupPipeline": {"type": "object", "additionalProperties": True},
                "cleanProposal": {"type": "object", "additionalProperties": True},
                "cleanGeometryAudit": {"type": "object", "additionalProperties": True},
                "canonicalization": {"type": "object", "additionalProperties": True},
                "quality": {"type": "object", "additionalProperties": True},
                "policy": {"type": "object", "additionalProperties": True},
                "integrity": _object(
                    {"cleanGeometryProposalHash": _sha256()},
                    ["cleanGeometryProposalHash"],
                ),
            },
            [
                "schemaVersion",
                "proposalId",
                "stageVersion",
                "garmentId",
                "garmentClass",
                "sourceRawProposalId",
                "sourceRawProposalHash",
                "sourceProviderRegistryId",
                "sourceProviderRegistryHash",
                "sourceRawTopologyReportId",
                "sourceRawTopologyReportHash",
                "sourceGeometryCleanupPlanId",
                "sourceGeometryCleanupPlanHash",
                "rawProposal",
                "cleanupPipeline",
                "cleanProposal",
                "cleanGeometryAudit",
                "canonicalization",
                "quality",
                "policy",
                "integrity",
            ],
        ),
        "raw-geometry-topology.schema.json": _schema(
            "Closy raw visual geometry topology diagnostics",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "reportId": {"type": "string", "pattern": "^topology\\."},
                "stageVersion": {"type": "string"},
                "analyzerVersion": {"type": "string"},
                "garmentId": {"type": "string", "pattern": "^garment\\."},
                "garmentClass": {"const": "tshirt"},
                "sourceRawProposalId": {"type": "string", "pattern": "^proposal\\."},
                "sourceRawProposalHash": _sha256(),
                "sourceRawAssetPath": _rel_path(),
                "sourceRawAssetHash": _sha256(),
                "sourceRawAssetByteSize": {"type": "integer", "minimum": 1},
                "providerId": {"type": "string"},
                "inputAudit": {"type": "object", "additionalProperties": True},
                "topology": {"type": "object", "additionalProperties": True},
                "cleanReadiness": {"type": "object", "additionalProperties": True},
                "policy": {"type": "object", "additionalProperties": True},
                "integrity": _object(
                    {"rawGeometryTopologyReportHash": _sha256()},
                    ["rawGeometryTopologyReportHash"],
                ),
            },
            [
                "schemaVersion",
                "reportId",
                "stageVersion",
                "analyzerVersion",
                "garmentId",
                "garmentClass",
                "sourceRawProposalId",
                "sourceRawProposalHash",
                "sourceRawAssetPath",
                "sourceRawAssetHash",
                "sourceRawAssetByteSize",
                "providerId",
                "inputAudit",
                "topology",
                "cleanReadiness",
                "policy",
                "integrity",
            ],
        ),
        "geometry-cleanup-plan.schema.json": _schema(
            "Closy geometry cleanup recommendation plan",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "reportId": {"type": "string", "pattern": "^cleanup_plan\\."},
                "stageVersion": {"type": "string"},
                "garmentId": {"type": "string", "pattern": "^garment\\."},
                "garmentClass": {"const": "tshirt"},
                "sourceRawProposalId": {"type": "string", "pattern": "^proposal\\."},
                "sourceRawProposalHash": _sha256(),
                "sourceRawTopologyReportId": {"type": "string", "pattern": "^topology\\."},
                "sourceRawTopologyReportHash": _sha256(),
                "topologySnapshot": {"type": "object", "additionalProperties": True},
                "recommendedOperations": {"type": "array", "items": {"type": "object"}},
                "execution": {"type": "object", "additionalProperties": True},
                "readiness": {"type": "object", "additionalProperties": True},
                "policy": {"type": "object", "additionalProperties": True},
                "integrity": _object(
                    {"geometryCleanupPlanHash": _sha256()},
                    ["geometryCleanupPlanHash"],
                ),
            },
            [
                "schemaVersion",
                "reportId",
                "stageVersion",
                "garmentId",
                "garmentClass",
                "sourceRawProposalId",
                "sourceRawProposalHash",
                "sourceRawTopologyReportId",
                "sourceRawTopologyReportHash",
                "topologySnapshot",
                "recommendedOperations",
                "execution",
                "readiness",
                "policy",
                "integrity",
            ],
        ),
        "provider-registry.schema.json": _schema(
            "Closy geometry provider registry",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "registryId": {"type": "string", "pattern": "^provider_registry\\."},
                "stageVersion": {"type": "string"},
                "garmentId": {"type": "string", "pattern": "^garment\\."},
                "garmentClass": {"const": "tshirt"},
                "sourceRecordId": {"type": "string", "pattern": "^capture\\."},
                "sourceRecordHash": _sha256(),
                "sourceVisualUnderstandingId": {"type": "string", "pattern": "^visual\\."},
                "sourceVisualRecordHash": _sha256(),
                "sourceFitReportId": {"type": "string", "pattern": "^fit\\."},
                "sourceFitReportHash": _sha256(),
                "sourceTextureIdentityId": {"type": "string", "pattern": "^texture\\."},
                "sourceTextureIdentityHash": _sha256(),
                "sourceGeometryProposalId": {"type": "string", "pattern": "^proposal\\."},
                "sourceGeometryProposalHash": _sha256(),
                "scope": {"type": "object", "additionalProperties": True},
                "selectedProviderId": {"type": "string"},
                "selectionReason": {"type": "string"},
                "providers": {"type": "array", "minItems": 1, "items": {"type": "object"}},
                "futureProviderSlots": {"type": "array", "items": {"type": "object"}},
                "manualImportCandidate": {"type": "object", "additionalProperties": True},
                "d0Capabilities": {"type": "object", "additionalProperties": {"type": "boolean"}},
                "policy": {"type": "object", "additionalProperties": True},
                "integrity": _object({"providerRegistryHash": _sha256()}, ["providerRegistryHash"]),
            },
            [
                "schemaVersion",
                "registryId",
                "stageVersion",
                "garmentId",
                "garmentClass",
                "sourceRecordId",
                "sourceRecordHash",
                "sourceVisualUnderstandingId",
                "sourceVisualRecordHash",
                "sourceFitReportId",
                "sourceFitReportHash",
                "sourceTextureIdentityId",
                "sourceTextureIdentityHash",
                "sourceGeometryProposalId",
                "sourceGeometryProposalHash",
                "scope",
                "selectedProviderId",
                "selectionReason",
                "providers",
                "futureProviderSlots",
                "manualImportCandidate",
                "d0Capabilities",
                "policy",
                "integrity",
            ],
        ),
        "avatar-contract.schema.json": _schema(
            "Closy avatar contract",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "avatarContractId": {"const": "avatar.closy_reference_v1"},
                "version": {"type": "string"},
                "displayName": {"type": "string"},
                "coordinateConvention": _coordinate_convention(),
                "heightMeters": {"type": "number", "minimum": 1.7, "maximum": 1.86},
                "pose": {"const": "T-pose"},
                "root": _vec(3),
                "grounded": {"type": "boolean"},
                "centeredXZ": {"type": "boolean"},
                "landmarks": {"type": "object", "additionalProperties": _vec(3)},
                "requiredLandmarks": {"type": "array", "items": {"type": "string"}},
                "measurements": {"type": "object", "additionalProperties": {"type": "number"}},
                "collisionPrimitives": {"type": "array", "items": {"type": "object"}},
                "capabilities": {"type": "object", "additionalProperties": {"type": "boolean"}},
                "meshTopologyHash": _sha256(),
                "meshContentHash": _sha256(),
                "collisionTopologyHash": _sha256(),
                "collisionContentHash": _sha256(),
                "provenance": {"type": "object", "additionalProperties": True},
            },
            [
                "schemaVersion",
                "avatarContractId",
                "coordinateConvention",
                "heightMeters",
                "landmarks",
                "collisionPrimitives",
                "capabilities",
                "meshTopologyHash",
                "meshContentHash",
                "collisionTopologyHash",
                "collisionContentHash",
                "provenance",
            ],
        ),
        "avatar-body-regions.schema.json": _schema(
            "Closy avatar body regions",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "avatarContractId": {"const": "avatar.closy_reference_v1"},
                "regions": {"type": "array", "items": {"type": "object"}},
            },
            ["schemaVersion", "avatarContractId", "regions"],
        ),
        "semantic-graph.schema.json": _schema(
            "Closy garment semantic graph",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "garmentId": {"type": "string"},
                "garmentClass": {"const": "tshirt"},
                "source": {"type": "object"},
                "components": {"type": "array", "items": {"type": "object"}},
                "partHierarchy": {"type": "object"},
                "panelMapping": {"type": "object"},
                "openings": {"type": "array", "items": {"type": "object"}},
                "seams": {"type": "array", "items": {"type": "object"}},
                "symmetry": {"type": "array", "items": {"type": "object"}},
                "requiredIds": {"type": "object"},
                "materialRegions": {"type": "array", "items": {"type": "string"}},
                "provenance": {"type": "object"},
            },
            [
                "schemaVersion",
                "garmentId",
                "garmentClass",
                "components",
                "panelMapping",
                "openings",
                "seams",
                "requiredIds",
                "provenance",
            ],
        ),
        "pattern.schema.json": _schema(
            "Closy garment pattern panels, curves, seams, and openings",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "garmentClass": {"const": "tshirt"},
                "parameters": {"type": "object", "additionalProperties": {"type": "number"}},
                "panels": {"type": "array", "items": {"type": "object"}},
                "seams": {"type": "array", "items": {"type": "object"}},
                "openings": {"type": "array", "items": {"type": "object"}},
                "provenance": {"type": "object"},
            },
            ["schemaVersion", "garmentClass", "parameters", "panels", "seams", "openings"],
        ),
        "simulation-mesh-manifest.schema.json": _mesh_manifest_schema(
            "Closy garment simulation mesh manifest"
        ),
        "constraints.schema.json": _schema(
            "Closy garment seam constraints",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "constraintModel": {"const": "seam_pairs_v1"},
                "constraints": {"type": "array", "items": {"type": "object"}},
                "derivableFutureConstraints": {"type": "array", "items": {"type": "string"}},
            },
            ["schemaVersion", "constraintModel", "constraints"],
        ),
        "material-physics.schema.json": _schema(
            "Closy authored material physics preset",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "presetId": {"type": "string"},
                "status": {"type": "string"},
                "units": {"const": "SI"},
                "surfaceDensityKgM2": {"type": "number"},
                "stretchStiffnessNPerM": {"type": "number"},
                "bendStiffnessNm": {"type": "number"},
                "dampingRatio": {"type": "number"},
                "frictionCoefficient": {"type": "number"},
                "thicknessMeters": {"type": "number"},
                "clothSettleRun": {"type": "boolean"},
                "settleBackend": {"type": "string"},
                "settleSolverVersion": {"type": "string"},
            },
            [
                "schemaVersion",
                "presetId",
                "status",
                "units",
                "surfaceDensityKgM2",
                "stretchStiffnessNPerM",
                "bendStiffnessNm",
                "dampingRatio",
                "frictionCoefficient",
                "thicknessMeters",
                "clothSettleRun",
                "settleBackend",
                "settleSolverVersion",
            ],
        ),
        "simulation-state.schema.json": _schema(
            "Closy deterministic simulation state",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "stateId": {"type": "string"},
                "solverVersion": {"type": "string"},
                "meshTopologyHash": _sha256(),
                "meshContentHash": _sha256(),
                "sourceContentHash": {"anyOf": [_sha256(), {"type": "null"}]},
                "diagnosticsRef": {"anyOf": [_rel_path(), {"type": "null"}]},
                "meshes": {
                    "type": "array",
                    "items": _object(
                        {
                            "name": {"type": "string"},
                            "panelId": {"type": "string"},
                            "positions": {"type": "array", "items": _vec(3)},
                        },
                        ["name", "panelId", "positions"],
                    ),
                },
            },
            [
                "schemaVersion",
                "stateId",
                "solverVersion",
                "meshTopologyHash",
                "meshContentHash",
                "sourceContentHash",
                "diagnosticsRef",
                "meshes",
            ],
        ),
        "settle-diagnostics.schema.json": _schema(
            "Closy deterministic cloth settle diagnostics",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "solverVersion": {"type": "string"},
                "backend": {"type": "string"},
                "convergenceState": {"enum": ["converged", "failed"]},
                "settings": {"type": "object", "additionalProperties": True},
                "elapsedTimeSeconds": {"type": "number"},
                "elapsedTimePolicy": {"type": "string"},
                "iterations": {"type": "integer"},
                "substeps": {"type": "integer"},
                "maximumSeamResidualMeters": {"type": "number"},
                "rmsSeamResidualMeters": {"type": "number"},
                "maximumBodyPenetrationMeters": {"type": "number"},
                "meanBodyPenetrationMeters": {"type": "number"},
                "collisionCount": {"type": "integer"},
                "invertedOrDegenerateElementCount": {"type": "integer"},
                "nonFiniteValueCount": {"type": "integer"},
                "maximumStrain": {"type": "number"},
                "meanStrain": {"type": "number"},
                "p95Strain": {"type": "number"},
                "energyHistory": {"type": "array", "items": {"type": "number"}},
                "selfCollision": _object(
                    {
                        "available": {"type": "boolean"},
                        "reason": {"type": "string"},
                    },
                    ["available", "reason"],
                ),
                "restTopologyHash": _sha256(),
                "settledTopologyHash": _sha256(),
                "restContentHash": _sha256(),
                "settledContentHash": _sha256(),
                "perPanelWarnings": {"type": "array", "items": {"type": "object"}},
                "perSeamWarnings": {"type": "array", "items": {"type": "object"}},
            },
            [
                "schemaVersion",
                "solverVersion",
                "backend",
                "convergenceState",
                "settings",
                "elapsedTimeSeconds",
                "elapsedTimePolicy",
                "iterations",
                "substeps",
                "maximumSeamResidualMeters",
                "rmsSeamResidualMeters",
                "maximumBodyPenetrationMeters",
                "meanBodyPenetrationMeters",
                "collisionCount",
                "invertedOrDegenerateElementCount",
                "nonFiniteValueCount",
                "maximumStrain",
                "meanStrain",
                "p95Strain",
                "energyHistory",
                "selfCollision",
                "restTopologyHash",
                "settledTopologyHash",
                "restContentHash",
                "settledContentHash",
                "perPanelWarnings",
                "perSeamWarnings",
            ],
        ),
        "render-mesh-manifest.schema.json": _mesh_manifest_schema(
            "Closy garment render mesh manifest"
        ),
        "render-materials.schema.json": _schema(
            "Closy garment render materials",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "materials": {"type": "array", "items": {"type": "object"}},
            },
            ["schemaVersion", "materials"],
        ),
        "binding-manifest.schema.json": _schema(
            "Closy sim-to-render binding manifest",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "format": {"const": "CLSYBND1"},
                "endianness": {"const": "little"},
                "headerSize": {"const": 96},
                "recordStride": {"const": 20},
                "recordLayout": {"type": "array", "items": {"type": "string"}},
                "sourceSimulationPath": _rel_path(),
                "targetRenderPath": _rel_path(),
                "simulationTopologyHash": _sha256(),
                "renderTopologyHash": _sha256(),
                "recordCount": {"type": "integer", "minimum": 1},
                "simulationTriangleCount": {"type": "integer", "minimum": 1},
                "panelTable": {"type": "array", "items": {"type": "string"}},
                "algorithm": {"type": "string"},
                "generationSettings": {"type": "object"},
                "reconstructionTolerance": {"type": "number"},
                "maximumReconstructionError": {"type": "number"},
                "rmsReconstructionError": {"type": "number"},
            },
            [
                "schemaVersion",
                "format",
                "endianness",
                "headerSize",
                "recordStride",
                "sourceSimulationPath",
                "targetRenderPath",
                "simulationTopologyHash",
                "renderTopologyHash",
                "recordCount",
                "panelTable",
                "algorithm",
                "reconstructionTolerance",
                "maximumReconstructionError",
                "rmsReconstructionError",
            ],
        ),
        "validation-report.schema.json": _schema(
            "Closy package validation issues and report",
            {
                "schemaVersion": {"const": SCHEMA_VERSION},
                "status": {"enum": ["passed", "failed", "pending"]},
                "counts": _object(
                    {
                        "info": {"type": "integer"},
                        "warning": {"type": "integer"},
                        "error": {"type": "integer"},
                        "fatal": {"type": "integer"},
                    },
                    ["info", "warning", "error", "fatal"],
                ),
                "issues": {"type": "array", "items": {"type": "object"}},
            },
            ["schemaVersion", "status", "counts", "issues"],
        ),
    }


def _schema(title: str, properties: dict[str, Any], required: list[str]) -> dict[str, Any]:
    filename = title.lower().replace(" ", "-")
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://closy.local/schemas/v1/{filename}.schema.json",
        "title": title,
        "type": "object",
        "additionalProperties": False,
        "required": required,
        "properties": properties,
    }


def _object(properties: dict[str, Any], required: list[str]) -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": required,
        "properties": properties,
    }


def _string_map(value_schema: dict[str, Any]) -> dict[str, Any]:
    return {"type": "object", "additionalProperties": value_schema}


def _coordinate_convention() -> dict[str, Any]:
    return _object(
        {
            "id": {"const": "closy-rh-yup-plus-z-v1"},
            "units": {"const": "metres"},
            "handedness": {"const": "right-handed"},
            "upAxis": {"const": "+Y"},
            "forwardAxis": {"const": "+Z"},
            "triangleWinding": {"const": "counter-clockwise-front-face"},
            "groundPlane": {"const": "Y=0"},
            "referenceAvatarRoot": {"const": "midpoint_between_grounded_feet_at_x0_z0"},
            "neutralFixturePose": {"const": "T-pose"},
        },
        [
            "id",
            "units",
            "handedness",
            "upAxis",
            "forwardAxis",
            "triangleWinding",
            "groundPlane",
            "referenceAvatarRoot",
            "neutralFixturePose",
        ],
    )


def _artifact_ref() -> dict[str, Any]:
    return _object(
        {
            "path": _rel_path(),
            "role": {"type": "string"},
            "canonical": {"type": "boolean"},
            "required": {"type": "boolean"},
            "mediaType": {"type": "string"},
            "byteSize": {"type": "integer", "minimum": 0},
            "sha256": _sha256(),
        },
        ["path", "role", "canonical", "required", "mediaType", "byteSize", "sha256"],
    )


def _capabilities() -> dict[str, Any]:
    keys = [
        "patternAvailable",
        "simulationReadyTopologyAvailable",
        "authoredMaterialPresetAvailable",
        "conventionalGlbAvailable",
        "simToRenderBindingAvailable",
        "bindingReconstructionValidated",
        "actualClothSettleAvailable",
        "selfCollisionAvailable",
        "sourceImageTextureAvailable",
        "sourceCaptureRecordAvailable",
        "captureQualityScored",
        "visualObservationsAvailable",
        "garmentMaskAvailable",
        "garmentLandmarksAvailable",
        "editableCorrectionRecordAvailable",
        "tshirtParameterFitAvailable",
        "fittingQualityScored",
        "textureIdentityEvidenceAvailable",
        "pbrMaterialObservationAvailable",
        "geometryProposalInterfaceAvailable",
        "rawGeometryProposalRecordAvailable",
        "geometryProposalQualityScored",
        "rawGeometryTopologyDiagnosticsAvailable",
        "geometryCleanupRecommendationAvailable",
        "providerProvenanceAvailable",
        "geometryProviderRegistryAvailable",
        "manualGeometryImportAdapterDeclared",
        "manualGeometryImportAssetAvailable",
        "externalGeometryProvidersConfigured",
        "cleanGeometryProposalAvailable",
        "personalizedAvatarAvailable",
        "skeletalFallbackAvailable",
        "zeroOneStaticAvailable",
        "zeroOneDynamicAvailable",
        "mobileOptimisedAuthoritativeAsset",
    ]
    return _object({key: {"type": "boolean"} for key in keys}, keys)


def _mesh_manifest_schema(title: str) -> dict[str, Any]:
    return _schema(
        title,
        {
            "schemaVersion": {"const": SCHEMA_VERSION},
            "meshRole": {"enum": ["simulation", "render"]},
            "coordinateConvention": _coordinate_convention(),
            "meshCount": {"type": "integer", "minimum": 1},
            "vertexCount": {"type": "integer", "minimum": 1},
            "triangleCount": {"type": "integer", "minimum": 1},
            "bounds": {"type": "object"},
            "topologyHash": _sha256(),
            "contentHash": _sha256(),
            "panelTable": {"type": "array", "items": {"type": "object"}},
            "meshes": {"type": "array", "items": {"type": "object"}},
            "edgeVertexMap": {"type": "object"},
            "panelCoordinatesRetained": {"const": True},
            "provenance": {"const": "procedural_fixture"},
        },
        [
            "schemaVersion",
            "meshRole",
            "coordinateConvention",
            "meshCount",
            "vertexCount",
            "triangleCount",
            "bounds",
            "topologyHash",
            "contentHash",
            "panelTable",
            "meshes",
            "panelCoordinatesRetained",
            "provenance",
        ],
    )


def _vec(length: int) -> dict[str, Any]:
    return {
        "type": "array",
        "minItems": length,
        "maxItems": length,
        "items": {"type": "number"},
    }


def _sha256() -> dict[str, str]:
    return {"type": "string", "pattern": HEX_64}


def _rel_path() -> dict[str, str]:
    return {"type": "string", "pattern": REL_PATH}
